### ISSUE TITLE
`make test` fails with non-informative error message

### ISSUE THREAD

**Issue by castarco** [nuta/kerla#69]
## Context:
OS: Ubuntu 21.10 64bits

## Problem
After upgrading my operating system, from Ubuntu 20.04 to Ubuntu 21.10 (and reinstalling some tools, like Docker, or qemu-*), and after building Kerla with the `make` command... I cannot test it via `make test`, instead, I have this error:

![Screenshot from 2021-11-09 15-36-20](https://user-images.githubusercontent.com/251364/140943942-270e8b30-726d-4d06-9762-8ad743346f52.png)

Any idea if there's any way to deal with this? I'm not sure it's really a bug, but so far it seems like it.

**Comment by nuta** [comment]
Could you try the latest main branch? Recently I've added a fix for it. The following is the reason why it prints only "fail":

This strange behavior stems from the implementation of unit test runner. Since it considers a test failed if a panic occurs (e.g. assertion failure), it has a special panic handler which prints `"fail"`:

https://github.com/nuta/kerla/blob/8f2fce6273d4f8a713344e33bcab42f031c540a6/kernel/test_runner.rs#L41

Thus, if a panic occurs before entering the test runner (`run_tests()`), you'll get such an informative error message.

**Comment by castarco** [comment]
It was solved, thx!
